<a href="https://colab.research.google.com/github/JonathanCecil01/MachineLearning/blob/master/MaliciousWebsites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np




In [ ]:

def correlation_plot(data):
    return
    


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/PDFMalware2022.csv")
data = data.dropna()
print(len(data))

print(data.columns)

10023
Index(['Fine name', 'pdfsize', 'metadata size', 'pages', 'xref Length',
       'title characters', 'isEncrypted', 'embedded files', 'images', 'text',
       'header', 'obj', 'endobj', 'stream', 'endstream', 'xref', 'trailer',
       'startxref', 'pageno', 'encrypt', 'ObjStm', 'JS', 'Javascript', 'AA',
       'OpenAction', 'Acroform', 'JBIG2Decode', 'RichMedia', 'launch',
       'EmbeddedFile', 'XFA', 'Colors', 'Class'],
      dtype='object')


In [ ]:
types = []
for i in data['Class']:
  if i=='Malicious':
    types.append(1)
  else:
    types.append(0)

data["Type"] = types

print(data["Type"])
corr  = data.corr()
corr.style.background_gradient(cmap='coolwarm')

0        1
1        1
2        1
3        1
4        1
        ..
10021    1
10022    1
10023    1
10024    1
10025    1
Name: Type, Length: 10023, dtype: int64


In [ ]:
for i in corr:
  if(corr["Type"][i]<-0.12):
    print(i)

pages
isEncrypted
stream
trailer
encrypt
ObjStm


In [ ]:
training = data.iloc[:7016, :]
test = data.iloc[7016:, :]
print(len(training))
print(len(test))



7016
3007


In [ ]:
logr = linear_model.LogisticRegression()
stream = np.array(training["pages"]).reshape(-1, 1)
types = np.array(training["Type"]).reshape(-1, 1)
logr.fit(stream,types)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
test_stream = np.array(test["pages"])#.reshape(-1, 1)
print(np.shape(test_stream))
test_stream = np.array(test["pages"]).reshape(-1, 1)
print(np.shape(test_stream))
y_actual = np.array(test["Type"]).reshape(-1, 1)
prediction = []
y_pred = logr.predict(test_stream)
print(y_pred)
print(y_actual)
test_stream = np.array(test["pages"]).reshape(3007,)
print(np.shape(test_stream))

(3007,)
(3007, 1)
[1 1 1 ... 1 1 1]
[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]
(3007,)


In [ ]:
#evaluation metrics

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_actual, y_pred)
print(cm)

[[  26 2810]
 [   0  171]]


In [ ]:
#Accuracy

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_actual, y_pred))

Accuracy :  0.06551380113069505
